  - name: Obtain Login
    include_vars: pass.yaml

  - name: Define cal-dc1-agg-n7k-gw Credentials
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        transport: nxapi
        #auth_pass: "{{ creds['auth_pass'] }}"

  - name: cal-dc1-agg-n7k-gw Config
    nxos_config:
      timeout: 100
      provider: "{{ provider }}"
      src: "~/HFT/roles/cal-dc1-agg-n7k-gw/files/vlan.cfg"